// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package pbs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseStudent_Type int32

const (
	ResponseStudent_Male   ResponseStudent_Type = 0
	ResponseStudent_Female ResponseStudent_Type = 1
)

var ResponseStudent_Type_name = map[int32]string{
	0: "Male",
	1: "Female",
}
var ResponseStudent_Type_value = map[string]int32{
	"Male":   0,
	"Female": 1,
}

func (x ResponseStudent_Type) String() string {
	return proto.EnumName(ResponseStudent_Type_name, int32(x))
}
func (ResponseStudent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_student_0ec08c0e30ea7b4f, []int{1, 0}
}

type RequestStudent struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestStudent) Reset()         { *m = RequestStudent{} }
func (m *RequestStudent) String() string { return proto.CompactTextString(m) }
func (*RequestStudent) ProtoMessage()    {}
func (*RequestStudent) Descriptor() ([]byte, []int) {
	return fileDescriptor_student_0ec08c0e30ea7b4f, []int{0}
}
func (m *RequestStudent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStudent.Unmarshal(m, b)
}
func (m *RequestStudent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStudent.Marshal(b, m, deterministic)
}
func (dst *RequestStudent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStudent.Merge(dst, src)
}
func (m *RequestStudent) XXX_Size() int {
	return xxx_messageInfo_RequestStudent.Size(m)
}
func (m *RequestStudent) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStudent.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStudent proto.InternalMessageInfo

func (m *RequestStudent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ResponseStudent struct {
	Id                   int32                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 ResponseStudent_Type `protobuf:"varint,4,opt,name=type,proto3,enum=pbs.ResponseStudent_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResponseStudent) Reset()         { *m = ResponseStudent{} }
func (m *ResponseStudent) String() string { return proto.CompactTextString(m) }
func (*ResponseStudent) ProtoMessage()    {}
func (*ResponseStudent) Descriptor() ([]byte, []int) {
	return fileDescriptor_student_0ec08c0e30ea7b4f, []int{1}
}
func (m *ResponseStudent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStudent.Unmarshal(m, b)
}
func (m *ResponseStudent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStudent.Marshal(b, m, deterministic)
}
func (dst *ResponseStudent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStudent.Merge(dst, src)
}
func (m *ResponseStudent) XXX_Size() int {
	return xxx_messageInfo_ResponseStudent.Size(m)
}
func (m *ResponseStudent) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStudent.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStudent proto.InternalMessageInfo

func (m *ResponseStudent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResponseStudent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResponseStudent) GetType() ResponseStudent_Type {
	if m != nil {
		return m.Type
	}
	return ResponseStudent_Male
}

func init() {
	proto.RegisterType((*RequestStudent)(nil), "pbs.RequestStudent")
	proto.RegisterType((*ResponseStudent)(nil), "pbs.ResponseStudent")
	proto.RegisterEnum("pbs.ResponseStudent_Type", ResponseStudent_Type_name, ResponseStudent_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudentClient is the client API for Student service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentClient interface {
	Get(ctx context.Context, in *RequestStudent, opts ...grpc.CallOption) (*ResponseStudent, error)
}

type studentClient struct {
	cc *grpc.ClientConn
}

func NewStudentClient(cc *grpc.ClientConn) StudentClient {
	return &studentClient{cc}
}

func (c *studentClient) Get(ctx context.Context, in *RequestStudent, opts ...grpc.CallOption) (*ResponseStudent, error) {
	out := new(ResponseStudent)
	err := c.cc.Invoke(ctx, "/pbs.Student/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServer is the server API for Student service.
type StudentServer interface {
	Get(context.Context, *RequestStudent) (*ResponseStudent, error)
}

func RegisterStudentServer(s *grpc.Server, srv StudentServer) {
	s.RegisterService(&_Student_serviceDesc, srv)
}

func _Student_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStudent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbs.Student/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).Get(ctx, req.(*RequestStudent))
	}
	return interceptor(ctx, in, info, handler)
}

var _Student_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbs.Student",
	HandlerType: (*StudentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Student_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student.proto",
}

func init() { proto.RegisterFile("student.proto", fileDescriptor_student_0ec08c0e30ea7b4f) }

var fileDescriptor_student_0ec08c0e30ea7b4f = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x48, 0x2a, 0x56, 0x52,
	0xe0, 0xe2, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0x86, 0x48, 0x0a, 0xf1, 0x71, 0x31,
	0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x28, 0x35, 0x31, 0x72,
	0xf1, 0x07, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0xa2, 0xaa, 0x61, 0x82, 0xa9, 0x11, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85,
	0x74, 0xb9, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x58, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0x24, 0xf5,
	0x0a, 0x92, 0x8a, 0xf5, 0xd0, 0xcc, 0xd1, 0x0b, 0xa9, 0x2c, 0x48, 0x0d, 0x02, 0x2b, 0x53, 0x92,
	0xe1, 0x62, 0x01, 0xf1, 0x84, 0x38, 0xb8, 0x58, 0x7c, 0x13, 0x73, 0x52, 0x05, 0x18, 0x84, 0xb8,
	0xb8, 0xd8, 0xdc, 0x52, 0x73, 0x41, 0x6c, 0x46, 0x23, 0x5b, 0x2e, 0x76, 0x98, 0xdd, 0x46, 0x5c,
	0xcc, 0xee, 0xa9, 0x25, 0x42, 0xc2, 0x50, 0x03, 0x91, 0xdd, 0x2e, 0x25, 0x82, 0xcd, 0x16, 0x25,
	0x86, 0x24, 0x36, 0xb0, 0x8f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x4a, 0x22, 0x7e,
	0x02, 0x01, 0x00, 0x00,
}
