// Code generated by protoc-gen-go. DO NOT EDIT.
// source: teacher.proto

package pbs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseTeacher_Type int32

const (
	ResponseTeacher_Male   ResponseTeacher_Type = 0
	ResponseTeacher_Female ResponseTeacher_Type = 1
)

var ResponseTeacher_Type_name = map[int32]string{
	0: "Male",
	1: "Female",
}
var ResponseTeacher_Type_value = map[string]int32{
	"Male":   0,
	"Female": 1,
}

func (x ResponseTeacher_Type) String() string {
	return proto.EnumName(ResponseTeacher_Type_name, int32(x))
}
func (ResponseTeacher_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_teacher_dd65920058f7c6b7, []int{1, 0}
}

type RequestTeacher struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestTeacher) Reset()         { *m = RequestTeacher{} }
func (m *RequestTeacher) String() string { return proto.CompactTextString(m) }
func (*RequestTeacher) ProtoMessage()    {}
func (*RequestTeacher) Descriptor() ([]byte, []int) {
	return fileDescriptor_teacher_dd65920058f7c6b7, []int{0}
}
func (m *RequestTeacher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTeacher.Unmarshal(m, b)
}
func (m *RequestTeacher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTeacher.Marshal(b, m, deterministic)
}
func (dst *RequestTeacher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTeacher.Merge(dst, src)
}
func (m *RequestTeacher) XXX_Size() int {
	return xxx_messageInfo_RequestTeacher.Size(m)
}
func (m *RequestTeacher) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTeacher.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTeacher proto.InternalMessageInfo

func (m *RequestTeacher) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ResponseTeacher struct {
	Id                   int32                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 ResponseTeacher_Type `protobuf:"varint,4,opt,name=type,proto3,enum=pbs.ResponseTeacher_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResponseTeacher) Reset()         { *m = ResponseTeacher{} }
func (m *ResponseTeacher) String() string { return proto.CompactTextString(m) }
func (*ResponseTeacher) ProtoMessage()    {}
func (*ResponseTeacher) Descriptor() ([]byte, []int) {
	return fileDescriptor_teacher_dd65920058f7c6b7, []int{1}
}
func (m *ResponseTeacher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseTeacher.Unmarshal(m, b)
}
func (m *ResponseTeacher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseTeacher.Marshal(b, m, deterministic)
}
func (dst *ResponseTeacher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseTeacher.Merge(dst, src)
}
func (m *ResponseTeacher) XXX_Size() int {
	return xxx_messageInfo_ResponseTeacher.Size(m)
}
func (m *ResponseTeacher) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseTeacher.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseTeacher proto.InternalMessageInfo

func (m *ResponseTeacher) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResponseTeacher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResponseTeacher) GetType() ResponseTeacher_Type {
	if m != nil {
		return m.Type
	}
	return ResponseTeacher_Male
}

func init() {
	proto.RegisterType((*RequestTeacher)(nil), "pbs.RequestTeacher")
	proto.RegisterType((*ResponseTeacher)(nil), "pbs.ResponseTeacher")
	proto.RegisterEnum("pbs.ResponseTeacher_Type", ResponseTeacher_Type_name, ResponseTeacher_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeacherClient is the client API for Teacher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeacherClient interface {
	Get(ctx context.Context, in *RequestTeacher, opts ...grpc.CallOption) (*ResponseTeacher, error)
}

type teacherClient struct {
	cc *grpc.ClientConn
}

func NewTeacherClient(cc *grpc.ClientConn) TeacherClient {
	return &teacherClient{cc}
}

func (c *teacherClient) Get(ctx context.Context, in *RequestTeacher, opts ...grpc.CallOption) (*ResponseTeacher, error) {
	out := new(ResponseTeacher)
	err := c.cc.Invoke(ctx, "/pbs.Teacher/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeacherServer is the server API for Teacher service.
type TeacherServer interface {
	Get(context.Context, *RequestTeacher) (*ResponseTeacher, error)
}

func RegisterTeacherServer(s *grpc.Server, srv TeacherServer) {
	s.RegisterService(&_Teacher_serviceDesc, srv)
}

func _Teacher_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTeacher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbs.Teacher/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServer).Get(ctx, req.(*RequestTeacher))
	}
	return interceptor(ctx, in, info, handler)
}

var _Teacher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbs.Teacher",
	HandlerType: (*TeacherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Teacher_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teacher.proto",
}

func init() { proto.RegisterFile("teacher.proto", fileDescriptor_teacher_dd65920058f7c6b7) }

var fileDescriptor_teacher_dd65920058f7c6b7 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x49, 0x4d, 0x4c,
	0xce, 0x48, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x48, 0x2a, 0x56, 0x52,
	0xe0, 0xe2, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0x81, 0x48, 0x0a, 0xf1, 0x71, 0x31,
	0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x28, 0x35, 0x31, 0x72,
	0xf1, 0x07, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0xa2, 0xaa, 0x61, 0x82, 0xa9, 0x11, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85,
	0x74, 0xb9, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x58, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0x24, 0xf5,
	0x0a, 0x92, 0x8a, 0xf5, 0xd0, 0xcc, 0xd1, 0x0b, 0xa9, 0x2c, 0x48, 0x0d, 0x02, 0x2b, 0x53, 0x92,
	0xe1, 0x62, 0x01, 0xf1, 0x84, 0x38, 0xb8, 0x58, 0x7c, 0x13, 0x73, 0x52, 0x05, 0x18, 0x84, 0xb8,
	0xb8, 0xd8, 0xdc, 0x52, 0x73, 0x41, 0x6c, 0x46, 0x23, 0x5b, 0x2e, 0x76, 0x98, 0xdd, 0x46, 0x5c,
	0xcc, 0xee, 0xa9, 0x25, 0x42, 0xc2, 0x50, 0x03, 0x91, 0xdd, 0x2e, 0x25, 0x82, 0xcd, 0x16, 0x25,
	0x86, 0x24, 0x36, 0xb0, 0x8f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x92, 0xcb, 0x65,
	0x02, 0x01, 0x00, 0x00,
}
