// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 请求查询用户
type RequestUser struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUser) Reset()         { *m = RequestUser{} }
func (m *RequestUser) String() string { return proto.CompactTextString(m) }
func (*RequestUser) ProtoMessage()    {}
func (*RequestUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b111af9438d78f8a, []int{0}
}
func (m *RequestUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUser.Unmarshal(m, b)
}
func (m *RequestUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUser.Marshal(b, m, deterministic)
}
func (dst *RequestUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUser.Merge(dst, src)
}
func (m *RequestUser) XXX_Size() int {
	return xxx_messageInfo_RequestUser.Size(m)
}
func (m *RequestUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUser.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUser proto.InternalMessageInfo

func (m *RequestUser) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type User struct {
	ID                   int32    `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Age                  int32    `protobuf:"varint,5,opt,name=Age,proto3" json:"Age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b111af9438d78f8a, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestUser)(nil), "user.RequestUser")
	proto.RegisterType((*User)(nil), "user.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// 获取用户，传入ID，返回用户信息
	GetUserInfo(ctx context.Context, in *RequestUser, opts ...grpc.CallOption) (*User, error)
	// 创建用户，传入用户信息，创建成功返回用户完整信息
	Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *RequestUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// 获取用户，传入ID，返回用户信息
	GetUserInfo(context.Context, *RequestUser) (*User, error)
	// 创建用户，传入用户信息，创建成功返回用户完整信息
	Create(context.Context, *User) (*User, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*RequestUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_b111af9438d78f8a) }

var fileDescriptor_user_b111af9438d78f8a = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x4f, 0xcb, 0x82, 0x40,
	0x10, 0x87, 0x5f, 0x75, 0x15, 0xde, 0x11, 0xa2, 0xe6, 0x10, 0x4b, 0x10, 0xc8, 0x9e, 0x3c, 0x79,
	0xa8, 0x4f, 0x10, 0x09, 0xe1, 0xa1, 0x0e, 0x56, 0x1f, 0x40, 0x73, 0x8a, 0x85, 0x6a, 0x6b, 0x5d,
	0xfb, 0xfc, 0xb1, 0x6b, 0x81, 0xdd, 0x9e, 0x79, 0x98, 0x3f, 0xbf, 0x01, 0xe8, 0x5a, 0xd2, 0xd9,
	0x43, 0x2b, 0xa3, 0x90, 0x59, 0x16, 0x73, 0x88, 0x4b, 0x7a, 0x76, 0xd4, 0x9a, 0x63, 0x4b, 0x1a,
	0x47, 0xe0, 0xcb, 0x86, 0x7b, 0x89, 0x97, 0x86, 0xa5, 0x2f, 0x1b, 0x71, 0x00, 0xf6, 0xf5, 0x45,
	0xce, 0xfd, 0xde, 0x17, 0x39, 0x22, 0xb0, 0x5d, 0x75, 0x23, 0x1e, 0x24, 0x5e, 0xfa, 0x5f, 0x3a,
	0xc6, 0x29, 0x44, 0x5b, 0x55, 0xcb, 0x2b, 0x71, 0xe6, 0xec, 0xa7, 0xc2, 0x31, 0x04, 0xab, 0x0b,
	0xf1, 0xd0, 0x0d, 0x5b, 0x5c, 0x54, 0x10, 0xdb, 0xad, 0x7b, 0xd2, 0x2f, 0x79, 0x22, 0xcc, 0x20,
	0xde, 0x90, 0xbb, 0x5f, 0xdc, 0xcf, 0x0a, 0x27, 0x99, 0x4b, 0x39, 0x88, 0x35, 0x83, 0x5e, 0x59,
	0x16, 0x7f, 0x28, 0x20, 0x5a, 0x6b, 0xaa, 0x0c, 0xe1, 0xc0, 0xff, 0xf6, 0xd4, 0x91, 0x7b, 0x72,
	0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x2d, 0x66, 0x9d, 0xf2, 0x00, 0x00, 0x00,
}
